language: go

sudo: false

matrix:
        include:
                - go: 1.x
                  env: LATEST=true
                - go: 1.9.x
                - go: 1.10.x
                - go: 1.11.x
                - go: 1.12.x
                - go: tip
        allow_failures:
                - go: tip

before_install:
        - go get github.com/mitchellh/gox
        - go get golang.org/x/lint/golint

install:
        - # skip

script:
        - go get -t -v ./...
        - diff -u <(echo -n) <(gofmt -d .)
        - go vet -v $(go list ./...)
        - go test -v -race ./...
        - golint -set_exit_status ./...
        - make all

deploy:
        provider: releases
        skip_cleanup: true
        api_key:
                secure: yzM8qZF/q26WZ5BOvPXyzt9lqt76PounE+n+LeiEWeWBWQfhtcV6zoR+Z1ocJ/wNKGY390QiST8DGRM1DtAsKnWv8XXqQ71yK4qYuDUhJqkKV40kPcVvPRJVtPYa7+2eMBhGdK1eenA+V6b8+J462BmRHEjPRscgF+oHnQnyrlr+6UsMF/3k0ilDmBBf8Qo3gMCasPO/JAHykTEQ0KzhnOUfVPjNlUmKFkDQN8eAiWicxSeHuBoqiTvYyqbA9cZz5HZQvPNYc3k0dtVjJnq/b93FqTyJW7+ThGIJ9DEeMYlzhjJJb2a9m5dXB1j4jW5anVIJPu7XaTqh5tOk5iHEM3IHTEVWeZZ74D7B5R6Dx9llr2BIp3c3XpANVR3MlDvi8+CcxTTkGjJ7es+sqaQ6g+jfBZK6bJOaaXN0R8LvJR/DDZ0cs4xpjO7gNdB+2iIm2Nz8YSXN83gUcZcFxjUfa4LJcfhwu6GL+i/eaTo8zJSBFWvcPvFSE8zc33Emhh+hvLKd+IIuotx5SjP14EpMvq7bYAC/1xjX4aFKXDmKT4yDbJC43NBjI22H4xQ/fA6fuGSiiaCJ3wZdECh9W+FPR36uET3xfS5qY/eieoB4piMx4JEegDFFBNpRJjM5VRkZybbw4gako9LkVQcTEYUc9WO4xI0hNeirhWikNYn8C4E=
        file_glob: true
        file: check_fritz.*.*
        on:
                repo: mcktr/check_fritz
                tags: true
                condition: $LATEST = true
