name: CI
on:
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15, 1.16, 1.x]
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Resolve Dependencies
        run: go get -v -t -d ./...

      - name: Go Test
        run: make test

      - name: Go Build
        run: make build

      - name: Test checksum
        run: make test-checksum

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: check_fritz_${{ matrix.go-version }}
          path: build/check_fritz*
